FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS base

USER root

COPY package*.json ./

RUN npm ci

FROM registry.access.redhat.com/ubi9/nodejs-20-minimal:latest AS final

COPY --from=base /opt/app-root/src/node_modules /opt/app-root/src/node_modules
COPY . /opt/app-root/src

USER root
RUN npm run build

RUN chown -R 1001:0 /opt/app-root/src

USER 1001

ENV NODE_ENV development
ENV PORT 3000

EXPOSE 3000

CMD ["npm", "start"]
