FROM fedora:40
USER root
RUN dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm && \
    dnf install -y python3.11 ffmpeg libSM libXext && \
    dnf clean all && \
    python3.11 -m ensurepip --upgrade

WORKDIR /app

COPY ../src/requirements.txt /app/requirements.txt
RUN python3.11 -m pip install --upgrade pip && \
    python3.11 -m pip install --no-cache-dir --upgrade -r requirements.txt

COPY ../src/frame_capture_client.py /app/frame_capture_client.py

EXPOSE 8500

ENTRYPOINT [ "streamlit", "run", "frame_capture_client.py" ]
